import type { ExperiencePackage } from "../types";

/**
 * ─────────────────────────────────────────────────────────────
 * PAQUETES DE COSTA RICA
 * Fuente de los paquetes nuevos: "Paquetes Kastell 27.pdf" (copia en /source-assets/paquetes).
 * Regla: solo se publica lo que dice la fuente. Lo que falte se deja sin llenar y se anota en
 * `reviewNotes` (notas internas) con `needsConfirmation: true`.
 * ─────────────────────────────────────────────────────────────
 */

const NO_THEME_PARKS = "Entradas a parques temáticos u otros destinos no mencionados en el paquete";

export const costaRicaPackages: ExperiencePackage[] = [
  {
    slug: "luna-de-miel-arenal-monteverde",
    kind: "itinerary",
    featured: true,
    popular: true,
    eyebrow: "Itinerario de autor",
    title: "Luna de miel entre volcanes y bosque nuboso",
    summary:
      "Cinco días para celebrar el amor entre aguas termales, lodo volcánico, puentes colgantes y el bosque nuboso de Monteverde.",
    description:
      "Diseñamos esta luna de miel para parejas que quieren vivir Costa Rica con intensidad y calma a la vez: amaneceres en la selva de San Carlos, la energía del Volcán Arenal, una cena especial bajo el vapor de las aguas termales y la emoción de volar sobre el bosque nuboso de Monteverde. Cada traslado, reserva y detalle queda en nuestras manos para que ustedes solo se dediquen a disfrutar.",
    categories: ["costa-rica"],
    types: ["romance", "aventura", "naturaleza", "bienestar"],
    destinations: ["San Carlos", "La Fortuna", "Monteverde"],
    destinationLabel: "San Carlos · La Fortuna · Monteverde",
    durationDays: 5,
    durationNights: 4,
    dateStatus: "not-provided",
    price: {
      amount: 1565,
      currency: "USD",
      prefix: "desde",
      per: "por persona",
      vat: "unspecified",
      note: "Precio de referencia por persona. Sujeto a cambios según temporada, disponibilidad y tamaño del grupo.",
    },
    availabilityStatus: "on-request",
    needsConfirmation: false,
    reviewNotes: ["Precio de referencia entregado por el cliente: no indica si incluye o no IVA."],
    // TODO: reemplazar con foto real del paquete Luna de Miel
    image: {
      src: "/images/paquete-luna-de-miel.jpg",
      alt: "Cascada rodeada de selva tropical en Costa Rica",
    },
    gallery: [
      // TODO: reemplazar con fotos reales del itinerario
      { src: "/images/puentes-colgantes.jpg", alt: "Puente colgante sobre el bosque tropical" },
      { src: "/images/monteverde-bosque.jpg", alt: "Bosque nuboso con luz filtrada entre los árboles" },
      { src: "/images/resort-selva.jpg", alt: "Piscina de un hotel boutique rodeada de selva" },
    ],
    highlights: [
      "Baños de barro volcánico y piscinas termominerales",
      "Tour en cuadraciclo por los cráteres del Volcán Arenal",
      "Cena especial en Ecotermales",
      "Puentes colgantes sobre el dosel del bosque",
      "Canopy de 16 cables en Monteverde, con Superman subterráneo",
    ],
    includes: [
      "4 noches de hospedaje en hoteles seleccionados",
      "Cóctel de bienvenida y tres tiempos de alimentación a la carta en San Carlos",
      "Desayunos en Monteverde",
      "Tours y actividades descritos en el itinerario",
      "Coordinación integral y acompañamiento antes, durante y después del viaje",
    ],
    itinerary: [
      {
        label: "Día 1",
        title: "Selva, barro volcánico y aguas termales",
        location: "San Carlos",
        description:
          "Llegan a un refugio rodeado de selva tropical donde el ritmo lo marca la naturaleza. La tarde es para consentirse: baños de barro volcánico al aire libre y acceso a las piscinas termominerales.",
        highlights: [
          "Cóctel de bienvenida",
          "Tres tiempos de alimentación a la carta",
          "Caminata guiada a las 6:00 a.m. al Proyecto de Rescate del Patrimonio Ancestral Villa Maleku",
        ],
      },
      {
        label: "Día 2",
        title: "La huella del Volcán Arenal",
        location: "La Fortuna",
        description:
          "Por la mañana, un recorrido en cuadraciclo por los cráteres que dejó la erupción del Volcán Arenal en 1968, el río de lodo volcánico, el mirador al Lago Arenal y los cultivos tradicionales de La Fortuna. Al caer la noche, Ecotermales: baño en aguas termales y una cena especial para dos.",
        highlights: [
          "Tour de cuadraciclos por los cráteres de 1968",
          "Mirador al Lago Arenal",
          "Aguas termales y cena especial en Ecotermales",
        ],
      },
      {
        label: "Día 3",
        title: "Caminar entre las copas de los árboles",
        location: "La Fortuna",
        description:
          "Un recorrido de dos horas por los puentes colgantes, entre senderos de paisajes espectaculares, para descubrir la vida del bosque desde las alturas.",
        highlights: ["Tour de puentes colgantes (2 horas)", "Senderos con vistas panorámicas"],
      },
      {
        label: "Días 4 – 5",
        title: "Monteverde, el bosque nuboso",
        location: "Monteverde",
        description:
          "Dos días rodeados de naturaleza en uno de los bosques nubosos más famosos del mundo. La gran aventura: un canopy de 16 cables —cinco de ellos entre 467 m y 1 km de largo, a alturas de 75 a 150 m— con rappel, Tarzan swing, Superman en cable y el Superman subterráneo, un túnel de 240 m bajo la montaña.",
        highlights: [
          "Canopy de 16 cables con rappel y Tarzan swing",
          "Superman en cable y Superman subterráneo (túnel de 240 m)",
          "Hospedaje con desayuno incluido",
        ],
      },
    ],
    whatsappMessage: "Hola, quiero cotizar el paquete Luna de Miel (5 días / 4 noches: San Carlos, La Fortuna y Monteverde).",
  },
  // ── Paquetes del PDF "Paquetes Kastell 27" ────────────────────────────────────────
  {
    slug: "paquete-essential",
    kind: "itinerary",
    popular: true,
    eyebrow: "Costa Rica · 5 días",
    title: "Paquete Essential",
    summary: "Cinco días entre San José y Arenal: dos noches en la capital, dos en Arenal y regreso a San José.",
    description:
      "Un recorrido corto para conocer lo esencial: dos noches en San José, dos noches en Arenal con experiencias naturales y entradas a termales, y regreso a San José.",
    categories: ["costa-rica"],
    types: ["naturaleza", "bienestar"],
    destinations: ["San José", "Arenal"],
    destinationLabel: "San José · Arenal",
    durationDays: 5,
    durationNights: 4,
    dateStatus: "not-provided",
    price: { amount: 1450, currency: "USD", per: "por persona", vat: "plus" },
    // TODO: reemplazar con foto real del paquete
    image: { src: "/images/resort-selva.jpg", alt: "Piscina de un hotel rodeada de selva tropical" },
    includes: [
      "Alojamiento en San José",
      "Alojamiento en Arenal",
      "Desayunos",
      "Experiencias naturales",
      "Entradas a termales",
      "Asistencia Kastell",
    ],
    itineraryKind: "nights",
    itinerary: [
      { label: "2 noches", title: "San José" },
      { label: "2 noches", title: "Arenal" },
      { label: "Regreso", title: "San José" },
    ],
    conditions: ["Precio por persona, más IVA."],
    availabilityStatus: "on-request",
    needsConfirmation: false,
    reviewNotes: [
      "El PDF no menciona transporte ni la línea 'No incluye entradas a parques temáticos…' en Essential (sí aparece en los otros paquetes). No se agregó ninguna de las dos.",
      "El PDF no detalla qué experiencias naturales incluye: se muestra el texto tal cual.",
    ],
    whatsappMessage: "Hola Kastell, quiero información del Paquete Essential (5 días / 4 noches, San José y Arenal).",
  },
  {
    slug: "nature-and-luxury",
    kind: "itinerary",
    popular: true,
    eyebrow: "Costa Rica · 7 días",
    title: "Nature & Luxury",
    summary: "Siete días por San José, Arenal y Monteverde, con transporte, termales y experiencias naturales.",
    description:
      "Seis noches entre San José, Arenal y Monteverde, con transporte, desayunos, experiencias naturales y entradas a termales.",
    categories: ["costa-rica"],
    types: ["naturaleza", "bienestar", "lujo"],
    destinations: ["San José", "Arenal", "Monteverde"],
    destinationLabel: "San José · Arenal · Monteverde",
    durationDays: 7,
    durationNights: 6,
    dateStatus: "not-provided",
    price: { amount: 2350, currency: "USD", per: "por persona", vat: "plus" },
    // TODO: reemplazar con foto real del paquete
    image: { src: "/images/monteverde-bosque.jpg", alt: "Bosque nuboso con luz filtrada entre los árboles" },
    includes: [
      "Transporte",
      "Alojamiento en San José",
      "Alojamiento en Arenal",
      "Alojamiento en Monteverde",
      "Desayunos",
      "Experiencias naturales",
      "Entradas a termales",
      "Asistencia Kastell",
    ],
    excludes: [NO_THEME_PARKS],
    itineraryKind: "nights",
    itinerary: [
      { label: "1 noche", title: "San José" },
      { label: "2 noches", title: "Arenal" },
      { label: "2 noches", title: "Monteverde" },
      { label: "1 noche", title: "San José" },
    ],
    conditions: ["Precio por persona, más IVA."],
    availabilityStatus: "on-request",
    needsConfirmation: false,
    whatsappMessage: "Hola Kastell, quiero información del paquete Nature & Luxury (7 días / 6 noches: San José, Arenal y Monteverde).",
  },
  {
    slug: "cultura-y-biodiversidad",
    kind: "itinerary",
    eyebrow: "Costa Rica · 9 días",
    title: "Cultura y biodiversidad",
    summary: "Nueve días por San José, Tortuguero, Arenal y Monteverde.",
    description: "Ocho noches entre San José, Tortuguero, Arenal y Monteverde, con experiencias naturales y entradas a termales.",
    categories: ["costa-rica"],
    types: ["naturaleza", "aventura"],
    destinations: ["San José", "Tortuguero", "Arenal", "Monteverde"],
    destinationLabel: "Tortuguero · Arenal · Monteverde",
    durationDays: 9,
    durationNights: 8,
    dateStatus: "not-provided",
    price: { amount: 2970, currency: "USD", per: "por persona", vat: "plus" },
    // TODO: reemplazar con foto real (Tortuguero / canales)
    image: { src: "/images/paquetes/stock-rio-palmeras.jpg", alt: "Río rodeado de palmeras en la selva tropical" },
    includes: [
      "Alojamiento en San José",
      "Alojamiento en Arenal",
      "Alojamiento en Monteverde",
      "Desayunos",
      "Experiencias naturales",
      "Entradas a termales",
      "Asistencia Kastell",
    ],
    excludes: [NO_THEME_PARKS],
    itineraryKind: "days",
    itinerary: [
      { label: "Día 1", title: "Llegada a San José" },
      { label: "Días 2–3", title: "Tortuguero" },
      { label: "Días 4–5", title: "Arenal" },
      { label: "Días 6–7", title: "Monteverde" },
      { label: "Día 8", title: "San José" },
      { label: "Día 9", title: "Salida" },
    ],
    itineraryNote: "Los servicios incluidos en Tortuguero (alojamiento, traslados y actividades) se confirman con Kastell al solicitar el paquete.",
    conditions: ["Precio por persona, más IVA."],
    availabilityStatus: "on-request",
    needsConfirmation: true,
    reviewNotes: [
      "PENDIENTE DE VALIDACIÓN (Tortuguero, días 2–3): el PDF lista Tortuguero en el itinerario pero NO en las inclusiones (solo San José, Arenal y Monteverde). Confirmar alojamiento, traslados, tours y transporte antes de publicar.",
      "El PDF no menciona transporte en este paquete.",
    ],
    whatsappMessage: "Hola Kastell, quiero información del paquete Cultura y biodiversidad (9 días / 8 noches, con Tortuguero).",
  },
  {
    slug: "100-aventura",
    kind: "itinerary",
    popular: true,
    eyebrow: "Costa Rica · 10 días",
    title: "100% Aventura",
    summary: "Diez días por San José, Poás, Doka, La Paz, Arenal, Monteverde y Manuel Antonio.",
    description: "Un recorrido de diez días por San José, Poás, Doka, La Paz, Arenal, Monteverde y Manuel Antonio, con alojamiento, desayunos, experiencias naturales y entradas a termales.",
    categories: ["costa-rica"],
    types: ["aventura", "naturaleza"],
    destinations: ["San José", "Poás", "Doka", "La Paz", "Arenal", "Monteverde", "Manuel Antonio"],
    destinationLabel: "Poás · Arenal · Monteverde · Manuel Antonio",
    durationDays: 10,
    dateStatus: "not-provided",
    price: { amount: 3500, currency: "USD", per: "por persona", vat: "plus" },
    // TODO: reemplazar con foto real del paquete
    image: { src: "/images/puentes-colgantes.jpg", alt: "Viajero cruzando un puente colgante entre montañas" },
    includes: [
      "Alojamiento en San José",
      "Alojamiento en Arenal",
      "Alojamiento en Monteverde",
      "Alojamiento en Manuel Antonio",
      "Desayunos",
      "Experiencias naturales",
      "Entradas a termales",
      "Asistencia Kastell",
    ],
    excludes: [NO_THEME_PARKS],
    itineraryKind: "days",
    itinerary: [
      { label: "Día 1", title: "Llegada a San José y recorrido por el centro de la ciudad" },
      { label: "Día 2", title: "Poás – Doka – La Paz" },
      { label: "Días 3–4", title: "Arenal" },
      { label: "Días 5–6", title: "Monteverde" },
      { label: "Días 7–8", title: "Manuel Antonio" },
      { label: "Día 9", title: "Regreso a San José" },
      { label: "Día 10", title: "Salida" },
    ],
    conditions: ["Precio por persona, más IVA."],
    availabilityStatus: "on-request",
    needsConfirmation: true,
    reviewNotes: [
      "DISCREPANCIA CON EL BRIEF: el brief dice que 100% Aventura incluye transporte, pero el PDF NO lo menciona en este paquete (solo alojamiento, desayunos, experiencias naturales, entradas a termales y asistencia Kastell). Se publicó lo que dice el PDF. Confirmar con el cliente si el transporte está incluido.",
      "El PDF indica '10 días' y no la cantidad de noches: no se publicó número de noches.",
    ],
    whatsappMessage: "Hola Kastell, quiero información del paquete 100% Aventura (10 días: San José, Poás, Arenal, Monteverde y Manuel Antonio).",
  },
  {
    slug: "rio-celeste-y-arenal",
    kind: "itinerary",
    eyebrow: "Especial de corta duración",
    title: "Río Celeste y Arenal",
    summary: "Tres días: San José, Alajuela y La Fortuna, Río Celeste y Arenal, con regreso a San José.",
    description: "Un especial de corta duración con alojamiento, transporte y desayunos.",
    categories: ["costa-rica"],
    types: ["naturaleza", "aventura"],
    destinations: ["La Fortuna", "Río Celeste", "Arenal"],
    destinationLabel: "La Fortuna · Río Celeste · Arenal",
    durationDays: 3,
    dateStatus: "not-provided",
    price: { amount: 850, currency: "USD", per: "por persona", vat: "plus" },
    // TODO: reemplazar con foto real de Río Celeste
    image: { src: "/images/paquetes/stock-cascada.jpg", alt: "Cascada entre vegetación tropical" },
    imagePosition: "50% 40%",
    includes: ["Alojamiento", "Transporte", "Desayunos"],
    excludes: [NO_THEME_PARKS],
    itineraryKind: "days",
    itinerary: [
      { label: "Día 1", title: "San José – Alajuela – Fortuna" },
      { label: "Día 2", title: "Río Celeste" },
      { label: "Día 3", title: "Arenal 68 – Regreso a San José" },
    ],
    conditions: ["Precio por persona, más IVA."],
    availabilityStatus: "on-request",
    needsConfirmation: false,
    reviewNotes: [
      "El PDF encabeza esta sección con 'Especiales Corta Duración' y el primer paquete no tiene nombre propio. Se interpretó como UN solo paquete (Río Celeste y Arenal) y no como dos ('Costa Rica corta duración' y 'Río Celeste/Arenal'). Confirmar el nombre comercial.",
      "El día 3 dice 'Arenal 68' tal cual en el PDF. Confirmar que se refiere al parque/atracción Arenal 68.",
      "El PDF no indica la cantidad de noches de este paquete.",
    ],
    whatsappMessage: "Hola Kastell, quiero información del especial Río Celeste y Arenal (3 días).",
  },
  {
    slug: "cr-pacifico",
    kind: "itinerary",
    eyebrow: "Especial de corta duración",
    title: "CR Pacífico",
    summary: "Tres días por el Pacífico Norte: tour de cocodrilos, catamarán, tour de chocolate y cabalgata.",
    description: "Un especial de corta duración con alojamiento, transporte y desayunos.",
    categories: ["costa-rica"],
    types: ["aventura", "naturaleza"],
    destinations: ["Pacífico Norte"],
    destinationLabel: "Pacífico Norte",
    durationDays: 3,
    dateStatus: "not-provided",
    price: { amount: 850, currency: "USD", per: "por persona", vat: "plus" },
    // TODO: reemplazar con foto real del Pacífico
    image: { src: "/images/contacto.jpg", alt: "Playa tropical con palmeras y arena blanca" },
    includes: ["Alojamiento", "Transporte", "Desayunos"],
    excludes: [NO_THEME_PARKS],
    itineraryKind: "days",
    itinerary: [
      { label: "Día 1", title: "San José – Pacífico Norte – Tour de cocodrilos" },
      { label: "Día 2", title: "Catamarán" },
      { label: "Día 3", title: "Tour de chocolate – Cabalgata – San José" },
    ],
    conditions: ["Precio por persona, más IVA."],
    availabilityStatus: "on-request",
    needsConfirmation: false,
    reviewNotes: ["El PDF no indica la cantidad de noches ni el hotel/zona exacta del Pacífico Norte."],
    whatsappMessage: "Hola Kastell, quiero información del especial CR Pacífico (3 días).",
  },
  {
    slug: "manuel-antonio",
    kind: "itinerary",
    eyebrow: "Especial de corta duración",
    title: "Manuel Antonio",
    summary: "Tres días entre San José y Manuel Antonio, con el segundo día en el Parque Nacional Manuel Antonio.",
    description: "Tres días entre San José y Manuel Antonio. El itinerario incluye el Parque Nacional Manuel Antonio.",
    categories: ["costa-rica"],
    types: ["naturaleza"],
    destinations: ["San José", "Manuel Antonio"],
    destinationLabel: "Manuel Antonio",
    durationDays: 3,
    dateStatus: "not-provided",
    price: { amount: 695, currency: "USD", per: "por persona", vat: "plus" },
    // TODO: reemplazar con foto real de Manuel Antonio
    image: { src: "/images/pilar-multidestino.jpg", alt: "Vista aérea de una playa de aguas turquesa" },
    includesNote: "Las inclusiones de este paquete se confirman con Kastell al solicitarlo.",
    itineraryKind: "days",
    itinerary: [
      { label: "Día 1", title: "San José – Manuel Antonio" },
      { label: "Día 2", title: "Parque Nacional Manuel Antonio" },
      { label: "Día 3", title: "Manuel Antonio – San José" },
    ],
    conditions: ["Precio por persona, más IVA."],
    availabilityStatus: "on-request",
    needsConfirmation: true,
    reviewNotes: [
      "INFORMACIÓN INCOMPLETA EN EL PDF: Manuel Antonio solo trae itinerario y precio ($695 + IVA). No hay 'Paquete incluye' ni 'No incluye' (en los otros paquetes sí). No se agregaron inclusiones. Pedir al cliente: alojamiento, transporte, desayunos, entrada al parque y exclusiones.",
      "Tampoco indica la cantidad de noches.",
    ],
    whatsappMessage: "Hola Kastell, quiero información del paquete Manuel Antonio (3 días).",
  },
  {
    slug: "boda-destino-a-la-medida",
    kind: "bespoke",
    eyebrow: "Destination Weddings",
    title: "Tu boda destino en Costa Rica",
    summary:
      "De la propuesta de locación al último baile: diseñamos, coordinamos y operamos cada momento de tu boda y la experiencia de tus invitados.",
    categories: ["costa-rica"],
    types: ["bodas", "romance", "lujo"],
    destinations: ["Guanacaste", "Pacífico Central", "Valle Central"],
    durationLabel: "A tu medida",
    // TODO: reemplazar con foto real de una boda Kastell
    image: { src: "/images/pilar-bodas.jpg", alt: "Pareja de recién casados celebrando al aire libre" },
    dateStatus: "not-provided",
    availabilityStatus: "on-request",
    needsConfirmation: false,
    whatsappMessage: "Hola, quiero información para mi boda destino en Costa Rica.",
    href: "/bodas-y-eventos",
  },
  {
    slug: "incentivos-corporativos",
    kind: "bespoke",
    eyebrow: "Corporate & Incentives",
    title: "Viajes de incentivo y reuniones de alto impacto",
    summary:
      "Programas para equipos y clientes clave: logística impecable, actividades que inspiran y momentos que fortalecen la cultura de tu empresa.",
    categories: ["costa-rica"],
    types: ["corporativo", "aventura", "lujo"],
    destinations: ["San José", "Guanacaste", "La Fortuna"],
    durationLabel: "A tu medida",
    // TODO: reemplazar con foto real de un evento corporativo Kastell
    image: { src: "/images/pilar-corporativo.jpg", alt: "Salón de conferencias preparado para un evento corporativo" },
    dateStatus: "not-provided",
    availabilityStatus: "on-request",
    needsConfirmation: false,
    whatsappMessage: "Hola Kastell, quiero cotizar un viaje corporativo o de incentivos.",
    href: "/bodas-y-eventos#corporativo",
  },
  {
    slug: "costa-rica-multidestino",
    kind: "bespoke",
    eyebrow: "Multidestination Travel",
    title: "Costa Rica de costa a costa",
    summary:
      "Volcanes, bosque nuboso, playas del Pacífico y el Caribe en un solo viaje, con el mismo estándar de lujo y coherencia en cada parada.",
    categories: ["costa-rica"],
    types: ["multidestino", "naturaleza", "lujo"],
    destinations: ["La Fortuna", "Monteverde", "Guanacaste", "Caribe Sur"],
    durationLabel: "A tu medida",
    // TODO: reemplazar con foto real
    image: { src: "/images/pilar-multidestino.jpg", alt: "Vista aérea de una playa de aguas turquesa" },
    dateStatus: "not-provided",
    availabilityStatus: "on-request",
    needsConfirmation: false,
    whatsappMessage: "Hola Kastell, quiero diseñar un viaje multidestino por Costa Rica.",
    href: "/contacto?experiencia=Multidestination",
  },
  {
    slug: "escapada-privada-de-lujo",
    kind: "bespoke",
    eyebrow: "Luxury Travel",
    title: "Escapada privada de lujo",
    summary:
      "Villas y hoteles boutique, traslados privados, bienestar y concierge: una Costa Rica íntima, exclusiva y hecha a tu ritmo.",
    categories: ["costa-rica"],
    types: ["lujo", "bienestar", "romance"],
    destinations: ["Guanacaste", "Pacífico Central"],
    durationLabel: "A tu medida",
    // TODO: reemplazar con foto real
    image: { src: "/images/pilar-luxury.jpg", alt: "Resort de lujo con piscina frente al mar" },
    dateStatus: "not-provided",
    availabilityStatus: "on-request",
    needsConfirmation: false,
    whatsappMessage: "Hola Kastell, quiero diseñar una escapada privada de lujo en Costa Rica.",
    href: "/contacto?experiencia=Luxury%20Travel",
  },
];
