import type { ExperiencePackage } from "../types";

/**
 * ─────────────────────────────────────────────────────────────
 * PAQUETES INTERNACIONALES
 * Fuente: flyers entregados por el cliente (copias en /source-assets/paquetes).
 * El texto de los flyers se transcribió como datos: las imágenes en /images/paquetes son recortes
 * de la foto principal, sin texto. Todo lo que no se pudo leer con seguridad queda en `reviewNotes`.
 * ─────────────────────────────────────────────────────────────
 */

const PASSPORT = "Los pasaportes requieren de un mínimo de 6 meses de vigencia para efectuar un viaje.";

export const internationalPackages: ExperiencePackage[] = [
  {
    slug: "crucero-caribe-enero-2027",
    kind: "itinerary",
    popular: true,
    eyebrow: "Crucero Grandeur of the Seas",
    title: "Crucero por el Caribe",
    summary: "Del 8 al 17 de enero de 2027: dos noches en ciudad y siete noches a bordo del Grandeur of the Seas, con vuelo desde San José.",
    description:
      "Paquete con tiquete aéreo San José / Panamá / San José, dos noches en ciudad con desayunos y siete noches a bordo del crucero Grandeur of the Seas, en cabina doble con vista al mar.",
    categories: ["internacionales", "cruceros"],
    types: ["multidestino", "lujo"],
    destinations: ["Caribe", "Panamá"],
    destinationLabel: "Caribe · Crucero Grandeur of the Seas",
    durationNights: 9,
    durationLabel: "9 noches (7 a bordo)",
    dateLabel: "Del 8 al 17 de enero de 2027",
    dateStatus: "confirmed",
    price: {
      amount: 2699,
      currency: "USD",
      per: "por persona",
      basis: "en cabina doble con vista al mar",
      vat: "included",
    },
    // Recorte de la foto del flyer (sin texto). TODO: reemplazar si el cliente entrega foto propia.
    image: { src: "/images/paquetes/crucero-caribe.jpg", alt: "Crucero Grandeur of the Seas navegando en aguas turquesa bajo un cielo con nubes" },
    imagePosition: "60% 50%",
    includes: [
      "Tiquete aéreo San José / Panamá / San José vía Avianca",
      "Impuestos aéreos + 1 equipaje documentado",
      "2 noches en ciudad con desayunos",
      "Traslado aeropuerto / hotel / puerto / hotel / aeropuerto",
      "7 noches a bordo del crucero Grandeur of the Seas",
      "Alimentación y bebidas incluidas a bordo",
      "Impuestos y propinas de la naviera",
    ],
    itineraryKind: "nights",
    itinerary: [
      { label: "2 noches", title: "Ciudad", description: "Con desayunos." },
      { label: "7 noches", title: "A bordo del crucero Grandeur of the Seas", description: "Alimentación y bebidas incluidas a bordo." },
    ],
    itineraryNote: "El recorrido por puertos y los detalles de la cabina se confirman con Kastell al solicitar el paquete.",
    conditions: [
      "Precio por persona, expresado en dólares americanos.",
      PASSPORT,
      "IVA incluido.",
      "Aplican otras condiciones.",
    ],
    availabilityStatus: "on-request",
    needsConfirmation: false,
    reviewNotes: [
      "Total de 9 noches = 2 en ciudad + 7 a bordo (el flyer no lo suma). Coincide con las fechas 8–17 de enero.",
      "El flyer dice solo 'Ciudad' para las 2 noches previas: no se asumió que sea Panamá. Falta el itinerario de puertos del crucero.",
      "El flyer no lista exclusiones ni la categoría de cabina más allá de 'doble vista al mar'.",
    ],
    whatsappMessage: "Hola Kastell, quiero información del Crucero por el Caribe (8 al 17 de enero de 2027, Grandeur of the Seas).",
  },
  {
    slug: "mexico-fin-de-ano",
    kind: "itinerary",
    eyebrow: "Ciudad de México",
    title: "México Fin de Año",
    summary: "Ocho noches en Ciudad de México con vuelo desde San José y cuatro tours con almuerzo.",
    description:
      "Paquete a Ciudad de México con tiquete aéreo vía Volaris, ocho noches de alojamiento, desayunos diarios, traslados y cuatro tours con almuerzo.",
    categories: ["internacionales", "mexico"],
    types: ["multidestino"],
    destinations: ["Ciudad de México", "Taxco", "Puebla", "Cholula", "Xochimilco", "Coyoacán", "Teotihuacán"],
    destinationLabel: "Ciudad de México",
    durationNights: 8,
    dateLabel: "Fecha por confirmar",
    dateStatus: "tbc",
    occupancyOptions: [
      { label: "Sencilla", amount: 1868 },
      { label: "Doble", amount: 1399 },
      { label: "Triple", amount: 1318 },
      { label: "Niño", amount: 1068 },
    ],
    price: { amount: 1068, currency: "USD", per: "por persona", basis: "según acomodación", vat: "included" },
    // Recorte de la foto del flyer (sin texto).
    image: { src: "/images/paquetes/mexico-fin-de-ano.jpg", alt: "Pirámides de Teotihuacán y el Ángel de la Independencia en Ciudad de México" },
    imagePosition: "50% 50%",
    includes: [
      "Tiquete aéreo San José / México / San José vía Volaris",
      "Impuestos aéreos + 1 equipaje documentado",
      "8 noches de alojamiento en Ciudad de México",
      "Desayunos diarios",
      "Traslado aeropuerto / hotel / aeropuerto",
      "Tour Grutas de Cacahuamilpa y Taxco con almuerzo",
      "Tour Puebla y Cholula con almuerzo",
      "Tour Xochimilco y Coyoacán con almuerzo",
      "Tour Basílica y Pirámides de Teotihuacán con almuerzo",
    ],
    itineraryNote: "El día a día y la fecha de salida se confirman con Kastell al solicitar el paquete.",
    conditions: [
      "Precio por persona según acomodación, expresado en dólares americanos.",
      "IVA incluido.",
      "No incluyen bebidas en los almuerzos.",
      "Tarifa niño de 2 a 10 años.",
      PASSPORT,
      "Aplican otras condiciones.",
    ],
    availabilityStatus: "on-request",
    needsConfirmation: true,
    reviewNotes: [
      "FECHA INCONSISTENTE EN EL FLYER: dice 'del 27 diciembre 2027 al 04 enero 2027' (el fin es anterior al inicio). No se corrigió: en la web aparece 'Fecha por confirmar'. Lo más probable es 27 dic 2026 – 4 ene 2027 (coincide con 8 noches), pero debe confirmarlo el cliente.",
      "El flyer no indica el número de días, solo '08 noches': no se publicó cantidad de días.",
      "En la tarjeta no se muestra un precio 'desde': se muestran las cuatro acomodaciones tal cual el flyer.",
    ],
    whatsappMessage: "Hola Kastell, quiero información del paquete México Fin de Año (8 noches en Ciudad de México). ¿Me confirman la fecha de salida?",
  },
  {
    slug: "ciudades-virreinales",
    kind: "itinerary",
    popular: true,
    eyebrow: "Querétaro · Guanajuato · Guadalajara · Ciudad de México",
    title: "Ciudades Virreinales",
    summary: "Del 27 de diciembre de 2026 al 5 de enero de 2027: nueve noches entre Querétaro, Guanajuato, Guadalajara y Ciudad de México.",
    description:
      "Recorrido por cuatro ciudades de México con tiquete aéreo vía Volaris, nueve noches de alojamiento, desayunos diarios, transporte terrestre y tours.",
    categories: ["internacionales", "mexico"],
    types: ["multidestino"],
    destinations: ["Querétaro", "Guanajuato", "Guadalajara", "Ciudad de México"],
    destinationLabel: "Querétaro · Guanajuato · Guadalajara · CDMX",
    durationNights: 9,
    dateLabel: "Del 27 de diciembre de 2026 al 5 de enero de 2027",
    dateStatus: "confirmed",
    occupancyOptions: [
      { label: "Sencilla", amount: 2279 },
      { label: "Doble", amount: 1686 },
      { label: "Triple", amount: 1567 },
      { label: "Niño", amount: 1173 },
    ],
    price: { amount: 1173, currency: "USD", per: "por persona", basis: "según acomodación", vat: "included" },
    // Recorte de la foto del flyer (sin texto).
    image: { src: "/images/paquetes/ciudades-virreinales.jpg", alt: "Parroquia de San Miguel Arcángel y plaza con árbol de Navidad en una ciudad virreinal de México" },
    imagePosition: "75% 50%",
    includes: [
      "Tiquete aéreo San José / México / San José vía Volaris con impuestos aéreos",
      "2 noches en Querétaro",
      "2 noches en Guanajuato",
      "2 noches en Guadalajara",
      "3 noches en Ciudad de México",
      "Desayunos diarios",
      "Traslado aeropuerto / hotel en Querétaro",
      "Traslado terrestre QRO, GTO, GDL, CDMX",
      "Transportación terrestre en todo el recorrido",
      "Tour de ciudad en GTO y GDL",
      "Tour Basílica y Pirámides de Teotihuacán con almuerzo",
    ],
    itineraryKind: "nights",
    itinerary: [
      { label: "2 noches", title: "Querétaro" },
      { label: "2 noches", title: "Guanajuato" },
      { label: "2 noches", title: "Guadalajara" },
      { label: "3 noches", title: "Ciudad de México" },
    ],
    conditions: [
      "Precio por persona según acomodación, expresado en dólares americanos.",
      "IVA incluido.",
      "No incluyen bebidas en los almuerzos.",
      "Tarifa niño de 2 a 10 años.",
      PASSPORT,
      "Aplican otras condiciones.",
    ],
    availabilityStatus: "on-request",
    needsConfirmation: false,
    reviewNotes: [
      "DISCREPANCIA CON EL BRIEF: el brief dice que incluye 'equipaje', pero el flyer de Ciudades Virreinales NO lo menciona (solo 'tiquete aéreo… con impuestos aéreos'). En México Fin de Año sí dice '1 equipaje documentado'. No se publicó equipaje. Confirmar.",
      "El flyer solo menciona traslado aeropuerto/hotel en Querétaro (sin traslado de regreso): se publicó tal cual.",
      "Las 9 noches se obtienen sumando 2+2+2+3; coinciden con las fechas 27 dic – 5 ene.",
      "Imagen duplicada: 'Paquete Ciudades Virreinales.png' y '(1).png' son idénticas (mismo contenido píxel a píxel). Se usa una sola.",
    ],
    whatsappMessage: "Hola Kastell, quiero información del paquete Ciudades Virreinales (27 de diciembre de 2026 al 5 de enero de 2027).",
  },
  {
    slug: "tesoros-coloniales-mexico-2026",
    kind: "itinerary",
    eyebrow: "México · 10 días / 9 noches",
    title: "Tesoros Coloniales México 2026",
    summary: "Ciudad de México, San Miguel de Allende, Guanajuato, Zacatecas, Guadalajara y Morelia en 10 días y 9 noches.",
    description:
      "Recorrido de 10 días y 9 noches por Ciudad de México, San Miguel de Allende, Guanajuato, Zacatecas, Guadalajara y Morelia, con transportación terrestre, desayunos diarios y guía acompañante.",
    categories: ["internacionales", "mexico"],
    types: ["multidestino"],
    destinations: ["Ciudad de México", "San Miguel de Allende", "Guanajuato", "Zacatecas", "Guadalajara", "Morelia"],
    destinationLabel: "Ciudad de México · San Miguel de Allende · Guanajuato · Zacatecas · Guadalajara · Morelia",
    durationDays: 10,
    durationNights: 9,
    dateLabel: "Fechas por confirmar",
    dateStatus: "not-provided",
    price: {
      amount: 1279,
      currency: "USD",
      prefix: "desde",
      per: "por persona",
      basis: "en ocupación doble",
      vat: "unspecified",
    },
    // Recorte de la foto del flyer (sin texto).
    image: { src: "/images/paquetes/tesoros-coloniales.jpg", alt: "Templo colonial de piedra rodeado de agaves en una plaza de México" },
    imagePosition: "50% 30%",
    includes: [
      "Traslados aeropuerto / hotel / aeropuerto en Ciudad de México",
      "9 noches de alojamiento",
      "Desayunos diarios",
      "Transportación terrestre México – San Miguel de Allende – Guanajuato – Zacatecas – Guadalajara – Morelia",
      "City tour, entrada al Museo de las Momias, destilería en Tequila, Mina del Edén y Teleférico",
      "Visitas: Querétaro, San Miguel de Allende, Guanajuato, Zacatecas, Tequila, Guadalajara, Pátzcuaro y Morelia",
      "Impuestos hoteleros",
      "Guía acompañante",
    ],
    itineraryKind: "nights",
    itinerary: [
      { label: "3 noches", title: "Ciudad de México" },
      { label: "1 noche", title: "San Miguel de Allende" },
      { label: "1 noche", title: "Guanajuato" },
      { label: "1 noche", title: "Zacatecas" },
      { label: "2 noches", title: "Guadalajara" },
      { label: "1 noche", title: "Morelia" },
    ],
    itineraryNote: "Las fechas de salida y el alcance de cada servicio se confirman con Kastell al solicitar el paquete.",
    conditions: ["No aplica para fechas de Mundial."],
    availabilityStatus: "on-request",
    needsConfirmation: true,
    reviewNotes: [
      "VIGENCIA: el flyer se llama 'México 2026' y advierte 'NO APLICA PARA FECHAS DE MUNDIAL' (junio–julio de 2026). Hoy es octubre de 2026: confirmar si el programa sigue vigente, con qué fechas y si el nombre debe cambiar. El flyer no trae fechas de salida.",
      "El flyer no indica si incluye vuelos internacionales (no se afirmó ni se negó) ni si el IVA está incluido o es adicional.",
      "TEXTO CORTADO EN LA IMAGEN: los íconos inferiores dicen 'Traslados Aeropuerto – Hotel –…' y 'Guía acompañante todo el…' (el texto se corta). El traslado se completó con la lista de la derecha, que sí dice 'aeropuerto / hotel / aeropuerto en Ciudad de México'. Para el guía se publicó solo 'Guía acompañante'; confirmar su alcance ('todo el recorrido'?).",
      "En la lista de la derecha, 'entrada a museo de las momias, destilería en Tequila, Mina del Edén y Teleférico' no deja claro si cada elemento incluye entrada: se transcribió casi literal.",
      "Las 9 noches suman 3+1+1+1+2+1 y coinciden con 9 noches del título.",
    ],
    whatsappMessage: "Hola Kastell, quiero información de Tesoros Coloniales México (10 días / 9 noches). ¿Qué fechas hay disponibles?",
  },
];
